apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lilsecret-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
